import { Item, OutfitSuggestion, WishlistItem } from '@/types/wardrobe';

export const mockItems: Item[] = [
  {
    id: '1',
    name: 'White Oxford Shirt',
    brand: 'Uniqlo',
    category: 'shirts',
    color: 'White',
    material: 'Cotton',
    season: ['spring', 'summer', 'fall'],
    purchaseDate: '2023-03-15',
    purchasePrice: 29.90,
    wearCount: 12,
    lastWorn: '2023-06-10',
    imageUrl: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?q=80&w=1925&auto=format&fit=crop',
    notes: 'Comfortable for daily wear',
    tags: ['casual', 'work', 'versatile'],
    cleaningStatus: 'clean',
  },
  {
    id: '2',
    name: 'Slim Fit Jeans',
    brand: 'Levi\'s',
    category: 'pants',
    color: 'Blue',
    material: 'Denim',
    season: ['spring', 'fall', 'winter'],
    purchaseDate: '2023-01-20',
    purchasePrice: 79.50,
    wearCount: 25,
    lastWorn: '2023-06-15',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=1926&auto=format&fit=crop',
    notes: 'Favorite pair, goes with everything',
    tags: ['casual', 'everyday', 'comfortable'],
    cleaningStatus: 'dirty',
  },
  {
    id: '3',
    name: 'Leather Bomber Jacket',
    brand: 'Zara',
    category: 'jackets',
    color: 'Brown',
    material: 'Leather',
    season: ['fall', 'winter'],
    purchaseDate: '2022-10-05',
    purchasePrice: 129.99,
    wearCount: 8,
    lastWorn: '2023-05-20',
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1935&auto=format&fit=crop',
    notes: 'Great for cool evenings',
    tags: ['casual', 'evening', 'statement'],
    cleaningStatus: 'clean',
  },
  {
    id: '4',
    name: 'Running Shoes',
    brand: 'Nike',
    category: 'shoes',
    color: 'Black/White',
    material: 'Synthetic',
    season: ['all'],
    purchaseDate: '2023-02-10',
    purchasePrice: 119.95,
    wearCount: 30,
    lastWorn: '2023-06-18',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1770&auto=format&fit=crop',
    notes: 'Comfortable for long runs',
    tags: ['athletic', 'running', 'workout'],
    cleaningStatus: 'clean',
  },
  {
    id: '5',
    name: 'Leather Watch',
    brand: 'Fossil',
    category: 'accessories',
    color: 'Brown/Silver',
    material: 'Leather/Metal',
    season: ['all'],
    purchaseDate: '2022-12-25',
    purchasePrice: 149.00,
    wearCount: 45,
    lastWorn: '2023-06-19',
    imageUrl: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=1888&auto=format&fit=crop',
    notes: 'Gift from family',
    tags: ['formal', 'everyday', 'accessory'],
    cleaningStatus: 'clean',
  },
  {
    id: '6',
    name: 'Bleu de Chanel',
    brand: 'Chanel',
    category: 'fragrances',
    color: 'N/A',
    material: 'N/A',
    season: ['all'],
    purchaseDate: '2023-04-02',
    purchasePrice: 120.00,
    wearCount: 20,
    lastWorn: '2023-06-19',
    imageUrl: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=1780&auto=format&fit=crop',
    notes: 'Signature scent for special occasions',
    tags: ['fragrance', 'evening', 'special'],
    cleaningStatus: 'clean',
  },
];

export const mockOutfitSuggestions: OutfitSuggestion[] = [
  {
    id: '1',
    name: 'Casual Friday',
    items: ['1', '2', '4'],
    occasion: 'casual',
    season: 'spring',
    imageUrl: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: '2',
    name: 'Night Out',
    items: ['3', '2', '5', '6'],
    occasion: 'evening',
    season: 'fall',
    imageUrl: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?q=80&w=1974&auto=format&fit=crop',
  },
];

export const mockWishlist: WishlistItem[] = [
  {
    id: '1',
    name: 'Cashmere Sweater',
    brand: 'Everlane',
    category: 'shirts',
    color: 'Navy',
    estimatedPrice: 120.00,
    priority: 'medium',
    url: 'https://www.everlane.com',
    notes: 'Wait for winter sale',
    imageUrl: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=1972&auto=format&fit=crop',
  },
  {
    id: '2',
    name: 'Chelsea Boots',
    brand: 'Thursday Boots',
    category: 'shoes',
    color: 'Brown',
    estimatedPrice: 199.00,
    priority: 'high',
    url: 'https://thursdayboots.com',
    notes: 'Need for fall season',
    imageUrl: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?q=80&w=1935&auto=format&fit=crop',
  },
];

export const mockAnalytics = {
  mostWorn: {
    category: 'shirts',
    item: 'White Oxford Shirt',
    count: 12,
  },
  leastWorn: {
    category: 'jackets',
    item: 'Leather Bomber Jacket',
    count: 8,
  },
  totalItems: 6,
  totalValue: 628.34,
  categoryBreakdown: [
    { category: 'shirts', count: 1 },
    { category: 'pants', count: 1 },
    { category: 'jackets', count: 1 },
    { category: 'shoes', count: 1 },
    { category: 'accessories', count: 1 },
    { category: 'fragrances', count: 1 },
  ],
  colorBreakdown: [
    { color: 'White', count: 1 },
    { color: 'Blue', count: 1 },
    { color: 'Brown', count: 1 },
    { color: 'Black/White', count: 1 },
    { color: 'Brown/Silver', count: 1 },
    { color: 'N/A', count: 1 },
  ],
};